name: CI/CD Pipeline - iara-api-chatbot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build e Push da imagem Docker
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/iara-api-chatbot
          IMAGE_TAG=${{ github.sha }}
          echo "Construindo imagem Docker: $IMAGE_NAME:$IMAGE_TAG"
          docker build -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          echo "Enviando imagem para o Docker Hub..."
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      - name: Deploy no Render
        if: success()
        run: |
          echo "Iniciando deploy no Render..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Notificação de sucesso
        if: success()
        run: echo "Deploy concluído com sucesso!"